### ISSUE TITLE
dq_init step looking for DQ_DEF extension in the wrong place?

### ISSUE THREAD

**Issue by shanosborne** [STScI-MESA/calibration-pipeline-testing-tool#6]
When running files through the dq_init test, my files fail at the test_dq_def_initialization function because it appears this step is looking for a DQ_DEF extension in the exposure image data and doesn't find anything. But there is not supposed to be a DQ_DEF extension in these images, only in the reference file, so I think this code is looking in the wrong place.

**Comment by mattjhill** [comment]
The DQ_DEF extension in sci files is something that instrument teams requested from the pipeline some time ago while we were discussing tests which is why there is a test checking for it.  I imagine it’s very low on the priority list of features and has not been implemented yet hence the failure.  I'll remove it until we get confirm this is actually going to be implemented.
